=== SteveLabrinos/msc-program-backend/controller/students.dtd
<!ELEMENT Students (Season,Student*)>
<!ELEMENT Season (#PCDATA)>
<!ELEMENT Student (FirstName,LastName,AverageGrade,CoursesPasses)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT AverageGrade (#PCDATA)>
<!ELEMENT CoursesPasses (#PCDATA)>

=== SteveLabrinos/msc-program-backend/controller/students_season_report.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Students SYSTEM "students.dtd">
<Students><Season>1</Season><Student><FirstName>Τάσος</FirstName><LastName>Ματσαμπλόκος</LastName><AverageGrade>7.33</AverageGrade><CoursesPasses>3</CoursesPasses><HighGrade/></Student><Student><FirstName>Γεώργιος</FirstName><LastName>Πεδαιμένος</LastName><AverageGrade>7.00</AverageGrade><CoursesPasses>1</CoursesPasses><HighGrade/></Student></Students>
